crudapp/blog_posts/urls.py
from django.conf.urls import url

from blog_posts import views

urlpatterns = [
  url(r'^$', views.post_list, name='post_list'),
  url(r'^new$', views.post_create, name='post_new'),
  url(r'^edit/(?P<pk>\d+)$', views.post_update, name='post_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.post_delete, name='post_delete'),
]

crudapp/crudapp/urls.py
"""crudapp URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
"""
from django.conf.urls import url, include
from django.contrib import admin
from crudapp.views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog_posts/', include('blog_posts.urls', namespace='blog_posts')),
    url(r'^$', home, name='home' ),
]

crudapp/blog_posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class blog_posts(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=400)
    tag = models.CharField(max_length=50)
    author = models.CharField(max_length=120)

    def __unicode__(self):
        return self.title

    def get_post_url(self):
        return reverse('post_edit', kwargs={'pk': self.pk})

crudapp/blog_posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from blog_posts.models import blog_posts
# Create your views here.

class PostsForm(ModelForm):
    class Meta:
        model = blog_posts
        fields = ['id', 'title', 'author']

def post_list(request, template_name='blog_posts/post_list.html'):
    posts = blog_posts.objects.all()
    data = {}
    data['object_list'] = posts
    return render(request, template_name, data)

def post_create(request, template_name='blog_posts/post_form.html'):
    form = PostsForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('blog_posts:post_list')
    return render(request, template_name, {'form': form})

def post_update(request, pk, template_name='blog_posts/post_form.html'):
    post = get_object_or_404(blog_posts, pk=pk)
    form = PostsForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('blog_posts:post_list')
    return render(request, template_name, {'form': form})

def post_delete(request, pk, template_name='blog_posts/post_delete.html'):
    post = get_object_or_404(blog_posts, pk=pk)
    if request.method=='POST':
        post.delete()
        return redirect('blog_posts:post_list')
    return render(request, template_name, {'object': post})

crudapp/crudapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

def home(request):
    html = """
    <h1>Django CRUD Example</h1>
    <a href="/blog_posts/">Blog post CRUD example</a><br>
    """
    return HttpResponse(html)

crudapp/blog_posts/templates/blog_posts/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application!</title>
  </head>
  <body>
    <div class="container">
      {% block content %}

      {% endblock %}
    </div>
  </body>
</html>

crudapp/blog_posts/templates/blog_posts/post_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application!</title>
  </head>
  <body>
    <div class="container">
      <form method="post">{% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input class="btn btn-primary" type="submit" value="Submit" />
      </form>
    </div>
  </body>
</html>

crudapp/blog_posts/templates/blog_posts/post_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application!</title>
  </head>
  <body>
    <div class="container">
      <form  method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Submit" />
      </form>
    </div>
  </body>
</html>

crudapp/blog_posts/templates/blog_posts/post_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
    <title>Django CRUD application!</title>
  </head>
  <body>
    <div class="container">
        <h1>Blog Post List!</h1>
        <ul>
          {% for post in object_list %}
          <li><p>Post ID: <a href="{% url "blog_posts:post_edit" post.id %}">{{ post.id }}</a></p>
          <p>Title: {{ post.title }}</p>
            <a href="{% url "blog_posts:post_delete" post.id %}">Delete</a>
          </li>
          {% endfor %}
        </ul>

        <a href="{% url "blog_posts:post_new" %}">New Blog post entry</a>
    </div>
  </body>
</html>